### ISSUE TITLE
Error in Browserified rewireJS

### ISSUE THREAD

**Issue by manikumar446** [jhnns/rewire#114]
I am started learning  Mocha unit testing framework with sinon as mocking library. I got a situation like, need to create stub on private java script function. So I install rewire to do that. I installed the browserify, as I am running my test cases in browser. But when i am trying to create bundle JS file using browserify, I am getting below error.
![capture](https://cloud.githubusercontent.com/assets/6083299/26775740/dd31206e-49f3-11e7-814c-d9b63c10e18d.PNG)
Then I installed coffee-script using npm. And then I successfully created the rewireBundle JS file and included it in SpecResult.html(which i am using to see test results in browser) file. But when I open SpecResults.html in browser, I am getting below errors.
![capture](https://cloud.githubusercontent.com/assets/6083299/26777743/e9f3e630-49fb-11e7-83f2-c0b07225e9f1.PNG)

I have attached sample project to ticket.
[mocha_sample.zip](https://github.com/jhnns/rewire/files/1051546/mocha_sample.zip)

**Comment by jhnns** [comment]
Rewire does not work with Browserify and Webpack out-of-the-box because it relies on the implementation of Node's CommonJS implementation. For Webpack, I've written the [rewire-webpack](https://github.com/jhnns/rewire-webpack) plugin. But for Browserify, there is no plugin and I do not plan to support it, sorry 😞
