### ISSUE TITLE
code coverage with nyc fails to cover all paths when using rewire@3

### ISSUE THREAD

**Issue by bforbis** [jhnns/rewire#131]
## Expected Behavior
`nyc` should cover all test paths when using `rewire@3` as a monkey-patching tool

## Observed Behavior
When in a project that has a dependency on `rewire@3`, `nyc` will sometimes not report all the covered code that gets executed. This behavior does not occur when using `rewire@2` or when using `istanbul@0.4.5`

## Bonus Points! Code (or Repository) that Reproduces Issue
I am not entirely clear on what exactly causes this issue. It doesn't happen all the time that rewire is being used, and load order of the files seems to matter.

Below is a repository I created that reproduces the issue in a relatively small number of files.
https://github.com/bforbis/istanbul-rewire-test

## Forensic Information

**Operating System:** macOS Sierra
**Environment Information:**
- node version: 8.9.1
- npm version: 5.5.1

## NYC issue tracker
This issue has been cross posted to the nyc github at istanbuljs/nyc/issues/747

**Comment by briandeheus** [comment]
I'd like to add this also happens on:

**Operating System:** Fedora Release 26
**Environment information:**
* node version: 6.11.5
* npm version: 3.10.10

Downgrading to `@2` works.

**Comment by brettstack** [comment]
@briandeheus which version of 2 works for you? I just installed 2.5.2 and it's still not covering.

OSX Node version 8.5.0

**Comment by alfred** [comment]
@brettstack Not the above, but I use OSX `rewire@2.5.2` with `node@8.9.0` and `npm@5.5.1` and it works for me. Double-check your tests?

**Comment by brettstack** [comment]
Thanks @alfred. I definitely get coverage when I remove rewire and the tests that require it. Will try downgrading again.

**Comment by umarrasydan** [comment]
Using ~2.5.2 works for me

no luck with @3

**Comment by GreensterRox** [comment]
I have the same issue: 

doesn't work with rewire @3 / nyc 11.6.0 / node 4.4.5

does work with rewire 2.5.2 / nyc 11.6.0 / node 4.4.5

**Comment by bforbis** [comment]
@jhnns I just confirmed that this has fixed the issue in my linked test repository. I also tested it on several of my private repos and saw that upgrading from `rewire@2` to `rewire@4` correctly preserves the code coverage from `nyc`, so looks like everything is working.

I'll note that in one of my repos I did start seeing an issue with running mocha/nyc of this nature:
```
 "before all" hook:
     Error: global leak detected: __core-js_shared__
```

I don't have a minimum reproduction I can share that caused this, but I was able to fix this issue by updating my mocha command to `mocha --require babel-register`. More info on that here: https://babeljs.io/docs/setup#installation

**Comment by jhnns** [comment]
@bforbis thanks. The `__core-js_shared__` property is used by [core.js](https://github.com/zloirock/core-js) to share instances of polyfills where it's important that there is only one instance per runtime (see [here](https://github.com/zloirock/core-js/issues/51)).

Since `rewire@2` and `rewire@4` are pretty similar, I guess the problem was introduced by a "hidden" update of your core-js module through transitive dependencies.

**Comment by brettstack** [comment]
I'm still not getting coverage when used with Jest. This definitely works when I remove rewire and all tests that use `.__set__`

**Comment by jhnns** [comment]
Can you provide a minimal reproducible example? :) That would help me to track down the bug.

**Comment by eran10** [comment]
i have similar issue, i am using rewire 4
but when i an running this command with nyc :
`nyc mocha --opts mocha/mocha.opts --forbid-only --require babel-polyfill --require babel-register && nyc report --reporter=text-lcov | coveralls`
it isn't working and in the response many errors like this : (all from before each step where i use rewire)
`at Object.load (node_modules/rewire/lib/moduleEnv.js:55:18)
      at internalRewire (node_modules/rewire/lib/rewire.js:49:15)
      at rewire (node_modules/rewire/lib/index.js:11:12)
      at Context.done ... `

if i just run 
`cross-env NODE_ENV=test mocha --opts mocha/mocha.opts` it work as expected, the issue is when using nyc to generate report for coverlls..

in rewire 2 all was working great, can someone please help ??

**Comment by chandlerlucius** [comment]
Just wanted to post my solution to this issue in case anyone else comes looking. What worked for me was to add a blank require line of the source file I was testing. Tested with jest --coverage (^24.8.0) and rewire module (^4.0.1).

Example:

const rewire = require('rewire');
const source = rewire('/js/source.js');
require('/js/source.js'); <----------------------------THIS LINE

describe('Test hello function - hello()', function () {
    const hello = source.__get__('hello');

    it('should print out the word hello', function () {
        expect(hello()).toBe('hello');
    });
});
