### ISSUE TITLE
rewire@4.0.0 broke tests

### ISSUE THREAD

**Issue by asamuzaK** [jhnns/rewire#136]
Hi, when I updated rewire from v3.0.2 to v4.0.0, tests are broken.
See job log [Build #386 - asamuzaK/withExEditorHost - Travis CI](https://travis-ci.org/asamuzaK/withExEditorHost/builds/364456820 "Build #386 - asamuzaK/withExEditorHost - Travis CI")

**Comment by jhnns** [comment]
Thanks for reporting this.

Unfortunately, I guess the behavior of `rewire@3` was actually more surprising. You're [surrounding your code with a curly braces](https://github.com/asamuzaK/withExEditorHost/blob/9d43d449b5a8a7e5d7ef773dfe336ed925566f06/index.js#L5), thus creating a block scope. rewire cannot access variables inside a block scope because that's impossible with pure JavaScript.

Your test was only possible with `rewire@3` because I used to transpile the code with babel which removed the block entirely I suppose. However, using babel for that job brings other problems as described [here](https://github.com/jhnns/rewire/commit/9b77ed9a293c538ec3eb5160bcb933e012ce517f).

I'd remove the curly braces around your module code because it's quite unusual and not necessary.

**Comment by asamuzaK** [comment]
OK I got it, thanks.
