### ISSUE TITLE
Security Issue with js-yaml coming from es-lint

### ISSUE THREAD

**Issue by carstenmuellerlemberg** [jhnns/rewire#172]
Hello,

currently an outdated eslint version is used containing "js-yaml": "^3.9.1" with a security issue.
Can you please update eslint version.

https://github.com/nodeca/js-yaml/pull/480#issue-267877885

**Comment by rensbaardman** [comment]
This is a duplicate of https://github.com/jhnns/rewire/issues/166.

There is already a PR for this (https://github.com/jhnns/rewire/pull/159), but it has been a while since the last PR was merged. If you really want to get rid of the warning right now, I have [a fork with updated dependencies](https://github.com/rensbaardman/rewire) (and some other slight improvements) which you could use.

**Comment by clsk** [comment]
Is this library not being maintained/supported any longer?

**Comment by cjancsar** [comment]
@clsk it does not appear so.
