### ISSUE TITLE
Add possibility to override require()

### ISSUE THREAD

**Issue by johnsonw** [jhnns/rewire#53]
Given the following code:

    var Agent = require('https').Agent;

    module.exports.agent = new Agent({
        maxSockets: 5
      });

We cannot overwrite Agent. However, in the following code we can overwrite Agent with a spy:

    var Agent = require('https').Agent;
    module.exports.agent = function () {
      return new Agent({
        maxSockets: 5
      });
    };

The difference is that the export is assigned to a function. It would be nice if we didn't have to assign the export to a function as the first block is cleaner.

**Comment by jhnns** [comment]
It doesn't work because currently rewire executes the module as usual. After that it provides setters and getters to change internal variables. You need to replace the `https` module *before* the module is executed.

Maybe that's possible, but then we'll need to add a second parameter to `rewire()`:

```javascript
var myAgent = rewire("./myAgent.js", {
    https: { Agent: agentMock }
});
```

**Comment by bendrucker** [comment]
This is exactly what proxyquire does. Only require manipulation to help isolate tests, no eval:

https://github.com/thlorenz/proxyquire

**Comment by jhnns** [comment]
Righty right

**Comment by jgrund** [comment]
This is sorely missed from this module. If we had this, we would not need to alter code structure to fit the tests.
