### ISSUE TITLE
Trouble rewiring hapi route handler functions

### ISSUE THREAD

**Issue by DigTheDoug** [jhnns/rewire#69]
I am trying to mock out some hapi route handlers so that I can test simply that the routes exist (functional details of routes to be handled in more full featured testing). I am having trouble getting the route handlers to be correctly overwritten. This could be an issue with hapi, or rewire, or my understanding of either's workings really.

I have a module that defines some routes like the following:
```
var routeHandler = function(request, reply){
    return reply("Ok");
};

module.exports.routes = [
    {
        method: 'GET',
        path: 'example',
        handler: routeHandler
    }
];
```

and then in my tests:
```
server = new Hapi.Server();
exampleRouter = rewire('routeModule');

console.log(exampleRouter.__get__('routeHandler'));   // [Function]
exampleRouter.__set__('routeHandler', 'test');
console.log(exampleRouter.__get__('routeHandler'));   // test

server.route(exampleRouter.routes);

//...

server.inject({
                method: 'GET',
                url: 'example'
            }, function(resp){
                expect(resp.statusCode).toBe(200);
                done();
            });
```

According to the logs, the routeHandler variable is getting overwritten, but when the route is called with the `server.inject`, it is still calling the original route handler function originally defined within the module.

Any idea on if maybe this issue is a way in hapi loads the routes or if there is something in the way that I am using rewire is incorrect or incompatible?

**Comment by jhnns** [comment]
That's normal JavaScript behavior :grinning: 

When you call `rewire('routeModule')`, the routeModule is executed. There, you store the reference to a function in the variable `routeHandler`. Additionally, you create an object with a property `handler` where the reference is *copied*. After that you change the variable `routeHandler` to point to the string `'test'`, but the copied reference on the `handler` property is *not* updated. That's why Hapi is still working with the original handler.

You're basically asking for pointers which are not available in JavaScript :wink:
